# Generated by Django 4.1 on 2022-10-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('director', models.CharField(default='', max_length=100)),
                ('resenia', models.TextField(null=True, verbose_name='Reseña')),
            ],
        ),
    ]
