# Generated by Django 4.1 on 2022-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
