# Generated by Django 4.1 on 2022-08-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='resenia',
            field=models.TextField(null=True, verbose_name='Reseña'),
        ),
    ]
