# Generated by Django 4.1 on 2022-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_pelicula_director_pelicula_resenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
