# Generated by Django 4.1 on 2022-10-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_pelicula_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='actor_1',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor_2',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor_3',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor_4',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor_5',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actor_6',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imdb',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre_alternativo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='nombre_ingles',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pais',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.CharField(max_length=50, null=True, verbose_name='Imagen'),
        ),
    ]
