# Generated by Django 4.1 on 2022-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_pelicula_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaXActor',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('id_actor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='id',
            new_name='id_pelicula',
        ),
    ]
